// Code generated by protoc-gen-go. DO NOT EDIT.
// source: structure/person.proto

package person

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PersonCreateRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Sex                  bool     `protobuf:"varint,3,opt,name=sex,proto3" json:"sex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PersonCreateRequest) Reset()         { *m = PersonCreateRequest{} }
func (m *PersonCreateRequest) String() string { return proto.CompactTextString(m) }
func (*PersonCreateRequest) ProtoMessage()    {}
func (*PersonCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_425cfd4b9f2eb9cc, []int{0}
}

func (m *PersonCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersonCreateRequest.Unmarshal(m, b)
}
func (m *PersonCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersonCreateRequest.Marshal(b, m, deterministic)
}
func (m *PersonCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonCreateRequest.Merge(m, src)
}
func (m *PersonCreateRequest) XXX_Size() int {
	return xxx_messageInfo_PersonCreateRequest.Size(m)
}
func (m *PersonCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PersonCreateRequest proto.InternalMessageInfo

func (m *PersonCreateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PersonCreateRequest) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *PersonCreateRequest) GetSex() bool {
	if m != nil {
		return m.Sex
	}
	return false
}

type PersonCreateResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PersonCreateResponse) Reset()         { *m = PersonCreateResponse{} }
func (m *PersonCreateResponse) String() string { return proto.CompactTextString(m) }
func (*PersonCreateResponse) ProtoMessage()    {}
func (*PersonCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_425cfd4b9f2eb9cc, []int{1}
}

func (m *PersonCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PersonCreateResponse.Unmarshal(m, b)
}
func (m *PersonCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PersonCreateResponse.Marshal(b, m, deterministic)
}
func (m *PersonCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PersonCreateResponse.Merge(m, src)
}
func (m *PersonCreateResponse) XXX_Size() int {
	return xxx_messageInfo_PersonCreateResponse.Size(m)
}
func (m *PersonCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PersonCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PersonCreateResponse proto.InternalMessageInfo

func (m *PersonCreateResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*PersonCreateRequest)(nil), "PersonCreateRequest")
	proto.RegisterType((*PersonCreateResponse)(nil), "PersonCreateResponse")
}

func init() { proto.RegisterFile("structure/person.proto", fileDescriptor_425cfd4b9f2eb9cc) }

var fileDescriptor_425cfd4b9f2eb9cc = []byte{
	// 174 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x2e, 0x29, 0x2a,
	0x4d, 0x2e, 0x29, 0x2d, 0x4a, 0xd5, 0x2f, 0x48, 0x2d, 0x2a, 0xce, 0xcf, 0xd3, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x57, 0xf2, 0xe5, 0x12, 0x0e, 0x00, 0xf3, 0x9d, 0x8b, 0x52, 0x13, 0x4b, 0x52, 0x83,
	0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18,
	0x15, 0x18, 0x35, 0x38, 0x83, 0xc0, 0x6c, 0x21, 0x01, 0x2e, 0xe6, 0xc4, 0xf4, 0x54, 0x09, 0x26,
	0x05, 0x46, 0x0d, 0xd6, 0x20, 0x10, 0x13, 0x24, 0x52, 0x9c, 0x5a, 0x21, 0xc1, 0xac, 0xc0, 0xa8,
	0xc1, 0x11, 0x04, 0x62, 0x2a, 0x69, 0x70, 0x89, 0xa0, 0x1a, 0x57, 0x5c, 0x90, 0x9f, 0x57, 0x0c,
	0x56, 0x99, 0x5b, 0x9c, 0x0e, 0x35, 0x0e, 0xc4, 0x34, 0xf2, 0xe6, 0xe2, 0x85, 0xa8, 0x0c, 0x4e,
	0x2d, 0x2a, 0xcb, 0x4c, 0x4e, 0x15, 0xb2, 0xe2, 0xe2, 0x74, 0x4c, 0x49, 0x81, 0x88, 0x09, 0x89,
	0xe8, 0x61, 0x71, 0x95, 0x94, 0xa8, 0x1e, 0x36, 0xc3, 0x95, 0x18, 0x92, 0xd8, 0xc0, 0x9e, 0x31,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x6f, 0xc4, 0x54, 0xb2, 0xe6, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PersonServiceClient is the client API for PersonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PersonServiceClient interface {
	AddPerson(ctx context.Context, in *PersonCreateRequest, opts ...grpc.CallOption) (*PersonCreateResponse, error)
}

type personServiceClient struct {
	cc *grpc.ClientConn
}

func NewPersonServiceClient(cc *grpc.ClientConn) PersonServiceClient {
	return &personServiceClient{cc}
}

func (c *personServiceClient) AddPerson(ctx context.Context, in *PersonCreateRequest, opts ...grpc.CallOption) (*PersonCreateResponse, error) {
	out := new(PersonCreateResponse)
	err := c.cc.Invoke(ctx, "/PersonService/AddPerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PersonServiceServer is the server API for PersonService service.
type PersonServiceServer interface {
	AddPerson(context.Context, *PersonCreateRequest) (*PersonCreateResponse, error)
}

func RegisterPersonServiceServer(s *grpc.Server, srv PersonServiceServer) {
	s.RegisterService(&_PersonService_serviceDesc, srv)
}

func _PersonService_AddPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PersonCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PersonServiceServer).AddPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/PersonService/AddPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PersonServiceServer).AddPerson(ctx, req.(*PersonCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PersonService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "PersonService",
	HandlerType: (*PersonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddPerson",
			Handler:    _PersonService_AddPerson_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "structure/person.proto",
}
